// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipalityTax.Data;

namespace MunicipalityTax.Data.Migrations
{
  [DbContext(typeof(MunicipalityContext))]
  partial class MunicipalityContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.1.9")
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("MunicipalityTax.Domain.Municipality", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int")
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<string>("Name")
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Municipalities");
          });

      modelBuilder.Entity("MunicipalityTax.Domain.TaxRule", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int")
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<DateTime>("End")
                      .HasColumnType("datetime2");

            b.Property<int>("MunicipalityId")
                      .HasColumnType("int");

            b.Property<double>("Rate")
                      .HasColumnType("float");

            b.Property<DateTime>("Start")
                      .HasColumnType("datetime2");

            b.Property<int>("Type")
                      .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("MunicipalityId");

            b.ToTable("TaxRules");
          });

      modelBuilder.Entity("MunicipalityTax.Domain.TaxRule", b =>
          {
            b.HasOne("MunicipalityTax.Domain.Municipality", null)
                      .WithMany("TaxRules")
                      .HasForeignKey("MunicipalityId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });
#pragma warning restore 612, 618
    }
  }
}
