// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tax.API.Contexts;

namespace Tax.API.Migrations
{
    [DbContext(typeof(KommuneContext))]
    partial class KommuneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tax.API.Entities.Kommune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Kommune");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5fd3ac8-e9c1-42f3-b3b2-451955d157b7"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("5ae87a5c-e9e1-4a6f-9941-17e072641704"),
                            Name = "Sønderborg"
                        },
                        new
                        {
                            Id = new Guid("0870ef4e-5d89-4cb4-95b8-a420463744ba"),
                            Name = "Vejle"
                        });
                });

            modelBuilder.Entity("Tax.API.Entities.TaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KommuneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KommuneId");

                    b.ToTable("TaxRule");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ea16e6c-92fc-405e-8a31-8f59ab80fd61"),
                            End = new DateTime(2016, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KommuneId = new Guid("b5fd3ac8-e9c1-42f3-b3b2-451955d157b7"),
                            Rate = 0.20000000000000001,
                            Start = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("e0967c75-dd92-482f-b5ec-f7f83f2fa998"),
                            End = new DateTime(2016, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KommuneId = new Guid("b5fd3ac8-e9c1-42f3-b3b2-451955d157b7"),
                            Rate = 0.40000000000000002,
                            Start = new DateTime(2016, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f9a8f089-a077-4169-a377-35d0ca259eff"),
                            End = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KommuneId = new Guid("b5fd3ac8-e9c1-42f3-b3b2-451955d157b7"),
                            Rate = 0.10000000000000001,
                            Start = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("be07f1e2-64d5-4ba6-9687-6be45abe82d5"),
                            End = new DateTime(2016, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KommuneId = new Guid("b5fd3ac8-e9c1-42f3-b3b2-451955d157b7"),
                            Rate = 0.10000000000000001,
                            Start = new DateTime(2016, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        });
                });

            modelBuilder.Entity("Tax.API.Entities.TaxRule", b =>
                {
                    b.HasOne("Tax.API.Entities.Kommune", "Kommune")
                        .WithMany("TaxRules")
                        .HasForeignKey("KommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
